DROP TABLE space_save;
CREATE TABLE space_save (
id NUMBER generated BY DEFAULT AS identity PRIMARY KEY,
uuid VARCHAR2(40) NOT NULL,
lives NUMBER NOT NULL,
points NUMBER NOT NULL,
scenestatus LONG NOT NULL,
invincible BOOLEAN,
totaltime NUMBER NOT NULL,
);